### PR TITLE
Repository update.

### PR DESCRIPTION
**Pull request by armm77**
Trinity repository update for Centos 8 and minor fixes.

### CODE REVIEW

**Comment by trunkmaster** [comment]
@armm77 What if we add building of missed CentOS packages in build script from CentOS git? What do you think?

**Comment by armm77** [comment]
@trunkmaster I was going to suggest that to you because with each external update the automation scripts and processes will fail, it is better to include the sources that are missing from your automation process.

**Comment by trunkmaster** [comment]
@armm77 I guess including of packages maintained by CentOS team is not a good idea. Actually we only need -devel part of system installed RPMs...

**Comment by armm77** [comment]
libart_lgpl-devel is currently only available for centos 7 and fedora 31 - 32 (official repositories), so it includes in the spec the trinity repository to download and fix the need for the centos 8 package, although I would prefer to use official packages from distributions or make your own packages.

But I leave it to your best judgment.

**Comment by trunkmaster** [comment]
You're right - libart is an exception. I'll think what I can do...

**Pull request closed without merging**
