### PR TITLE
Applications/Login: Fix variable initialization in systemd service

### LINKED ISSUE #347: System/etc/profile.d/nextspace.sh is not suitable as EnvironmentFile in Applications/Login/Resources/loginwindow.service
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile= is quite clear that files passes in as EnvironmentFile must only contain Key=Value pairs, not full blown shell scripts.

https://unix.stackexchange.com/questions/358998/systemd-environmentfile-re-using-variables-how/431863 proposes `ExecStart=/bin/bash -ac '. /path/to/env_file; exec /path/to/program'` as a workaround.

### PR DESCRIPTION
**Pull request by pgeorgi**
Closes #347

### CODE REVIEW

**Comment by trunkmaster** [comment]
@pgeorgi actually we can just completly remove `EnvironmentFile=`line and leave `ExecStart=` as it is. User session environment variable are set in UserSession's `_setUserEnvironment`.

**Comment by pgeorgi** [comment]
Doesn't Login.App need some of them configured, too?

**Comment by trunkmaster** [comment]
No. To start Login.app needs libraries (path to them are confiigured in /etc/ld.so.conf.d/nextspace.conf) and defaults file (located in app's bundle). That simple.
/etc/profile.d/nextspace.sh really useful for shells (e.g. in Terminal.app) and is read by Bourne-style shells (zsh, bash).

**Comment by pgeorgi** [comment]
I verified that Login.app works without those variables and with an empty ~root/Library (it generates a few files in that case, e.g. Login.plist), so I dropped all mentions of changing the environment.

**Comment by trunkmaster** [comment]
Thank you, merging. Please do not forget to close #347.

**Pull request merged**
