### PR TITLE
Adjust Debian Packaging for Debian stable/Buster

### PR DESCRIPTION
**Pull request by Letterus**
This PR contains changes to enable building for Debian stable. Aim is a build für Raspbian/armhf.

### CODE REVIEW

**Review by Letterus — COMMENTED** [review]
Changed.

**Comment by trunkmaster** [comment]
@Letterus thanks. I feel we should call for Debian packaging master - @pgeorgi. What do you think?

**Comment by Letterus** [comment]
> @Letterus thanks. I feel we should call for Debian packaging master - @pgeorgi - for review. What do you think?

@trunkmaster Yes, of course. We're talking to each other. Think he'll test the changes the next days.

**Comment by alexmyczko** [comment]
Will there be updates for debian/buster and debian/arm64 (runs on raspberry pi hardware)

**Comment by Letterus** [comment]
I once intended this, but I do work on this project anymore.

**Comment by trunkmaster** [comment]
@Letterus I saw your mailing list post. It's quite sad to know that you quit GNUstep development. Although I want to notice that NEXTSPACE is separate project with no relation to GNUstep - it just uses GNUstep libraries.

**Comment by Letterus** [comment]
@trunkmaster Thank you for your kind words. I know. But I think it is not possible to even develop a GNUstep app without contributing to the GNUstep project/libs. Therefor I now prefer to develop for ObjFW and elementary OS. Sorry, but all the best to you and your project.

**Comment by Letterus** [comment]
My changes are outdated since some time. Closing this PR.

**Pull request closed without merging**
