### PR TITLE
implement "open in workspace" service

### PR DESCRIPTION
**Pull request by onflapp**

### CODE REVIEW

**Comment by trunkmaster** [comment]
@onflapp could you please describe some use cases of this service?

**Comment by onflapp** [comment]
"Open in Workspace" service allows other applications to open directory or file in Workspace app.
This can be either done by selecting a path as a text or programmatically via NSPerformService.

Use case:
- open current directory from Terminal 
   shell usually shows current directory as part of its prompt, select it and call the service

This functionality is equivalent to "Open in Workspace" service in NextStep and  similar to "Show in Finder" in OS X

**Comment by onflapp** [comment]
@trunkmaster NextSpace could go even further.
Imagine you could simply do "ls" 
select a file name (not full path) and call "Open in Workspace" or "Open in Preview"
Terminal could create full path based on its current directory.
This could be taken from the title (Mac OS use to do that) or via special escape sequence as Apple's Terminal does it.

**Comment by trunkmaster** [comment]
@onflapp Nice examples, thanks.

I guess you know about NSWorkspace AppKit's class. Some methods of this class is meant to be supported by "Workspace" application. For example, `[[NSWorkspace sharedWorkspace] openFile:@"/Users/me"]` should open new File View window rooted at /Users/me. That's how NextStep/OPENSTEP Terminal application implements "Open in Workspace". If you open "Services" submenu of Edit application on OPENSTEP you can't see "Open in Workspace". There's no Services->Workspace submenu either.

Saying that I mean that we don't need to implement Workspace service of any kind. Workspace application API - unlike other applications - is exposed via NSWorkspace class. So if we want "Open in Workspace" in Terminal's "Services" menu we need to implement this functionality in Terminal. You can find examples of NSWorkspace usage in OpenUp application.

**Pull request merged**
