### PR TITLE
Install global default files on Debian

### LINKED ISSUE #267: Install global defaults on Debian
There are some global defaults that should be installed on Debian but aren't.

### PR DESCRIPTION
**Pull request by pgeorgi**
This introduces a new package "nextspace" that installs a couple of global files (e.g. the global defaults and shell defaults in /etc/profile.d) and also depends on the apps of the basic nextspace desktop: Login, Workspace, Terminal, TextEdit, TimeMon.

For the global defaults file the base commit for nextspace had to be uprevved.

Fixes #267

### CODE REVIEW

**Comment by trunkmaster** [comment]
I make `nextspace-core` RPM for that purpose (look into [nextspace-core.spec](https://github.com/trunkmaster/nextspace/blob/master/Libraries/core/nextspace-core.spec)). I made nextspace-core dependency for nextspace-frameworks and nextspace-applications so if you have installed applications all these global files shoudl be installed automatically.

In your implementation somebody may install Workspace without essential global defaults. It may lead to weird behaviour of application (even to crash if GNUstep backend is not set up correctly).

**Comment by trunkmaster** [comment]
@pgeorgi ?

**Comment by pgeorgi** [comment]
Sorry, busy with other things right now. will get to it in a few days, I hope. But yes, I agree that your dependency scheme is better.

**Comment by pgeorgi** [comment]
Alright, I finally managed to update the patches. They cover the latest master branch now, so the "update to lastest master" commit is a fair bit larger. It also allows building on current Debian sid where some package dependencies have changed.

In terms of the nextspace source package, it now generates nextspace-core containing the config files and nextspace-desktop, a meta-package to easily install the entire desktop.

**Pull request merged**
